services:
  tpat:
    build:
      context: ./tpat
      dockerfile: Dockerfile
    container_name: tpat
    restart: unless-stopped
    depends_on:
      - tpatDatabase
    ports:
      - "8009:8009"
      - "8080:8080"
    mem_limit: 4g
    logging:
      options:
        max-size: "5m"
        max-file: "3"
      driver: "json-file"
    volumes: 
      - /opt/tpat/files
      - /opt/tpat/lucene

  tat:
    build:
      context: ./tat
      dockerfile: Dockerfile
    container_name: tat
    restart: unless-stopped
    depends_on:
      - tatDatabase
    ports:
      - "8109:8009"
      - "8081:8080"
    mem_limit: 4g
    logging:
      options:
        max-size: "15m"
        max-file: "3"
      driver: "json-file"
    volumes: 
      - /Users/jk90/opt/trustmarks/tat/files:/opt/tat/files
      - /Users/jk90/opt/trustmarks/tat/files:/opt/tat/lucene

  tbr:
    build:
      context: ./tbr
      dockerfile: Dockerfile
    container_name: tbr
    restart: unless-stopped
    depends_on:
      - tbrDatabase
    ports:
      - "8209:8009"
      - "8082:8080"
    mem_limit: 4g
    logging:
      options:
        max-size: "15m"
        max-file: "3"
      driver: "json-file"
    volumes: 
      - /opt/tbr/files
      - /opt/tbr/lucene

  trpt:
    build:
      context: ./trpt
      dockerfile: Dockerfile
    container_name: trpt
    restart: unless-stopped
    depends_on:
      - trptDatabase
    ports:
      - "8309:8009"
      - "8083:8080"
    mem_limit: 4g
    logging:
      options:
        max-size: "15m"
        max-file: "3"
      driver: "json-file"
    volumes: 
      - /opt/trpt/files
      - /opt/trpt/lucene

  tpatDatabase:
    image: mariadb:10.3
    container_name: tpatDatabase
    restart: unless-stopped
    ports:
    - "3356:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=tpat_user \"--password=tpat_pw_11\" --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
    - MYSQL_USER=tpat_user
    - MYSQL_PASSWORD=tpat_pw_11
    - MYSQL_ROOT_PASSWORD=tpat_pw_11
    - MYSQL_DATABASE=tpat_db


  tatDatabase:
    image: mariadb:10.3
    container_name: tatDatabase
    restart: unless-stopped
    ports:
      - "3456:3306"
    volumes:
      - /Users/jk90/opt/trustmarks/tat/db:/var/lib/mysql
    healthcheck:
      test: "/usr/bin/mysql --user=tat_user \"--password=tat_pw_11\" --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
    - MYSQL_USER=tat_user
    - MYSQL_PASSWORD=tat_pw_11
    - MYSQL_ROOT_PASSWORD=tat_pw_11
    - MYSQL_DATABASE=tat_db

  tbrDatabase:
    image: mariadb:10.3
    container_name: tbrDatabase
    restart: unless-stopped
    ports:
    - "3556:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=tbr_user \"--password=tbr_pw_11\" --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
    - MYSQL_USER=tbr_user
    - MYSQL_PASSWORD=tbr_pw_11
    - MYSQL_ROOT_PASSWORD=tbr_pw_11
    - MYSQL_DATABASE=tbr_db

  trptDatabase:
    image: mariadb:10.3
    container_name: trptDatabase
    restart: unless-stopped
    ports:
    - "3656:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=trpt_user --password=trpt_pw_11 --execute \"SHOW DATABASES;\""
      interval: 5s
      timeout: 2s
      retries: 5
    environment:
    - MYSQL_USER=trpt_user
    - MYSQL_PASSWORD=trpt_pw_11
    - MYSQL_ROOT_PASSWORD=trpt_pw_11
    - MYSQL_DATABASE=trpt_db

